# Generated by Django 3.0.6 on 2020-05-22 13:24

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='post_img/')),
                ('slug', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('view', models.IntegerField(default=0)),
                ('group', models.ManyToManyField(to='blog.Group')),
            ],
        ),
    ]
